# Generated by Django 4.2.9 on 2026-07-04 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsappInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Friendly label, e.g. 'Sales', 'Support'",
                        max_length=255,
                    ),
                ),
                (
                    "phone_number_id",
                    models.CharField(
                        help_text="Phone Number ID from Meta Developer Console",
                        max_length=255,
                    ),
                ),
                (
                    "whatsapp_business_account_id",
                    models.CharField(
                        help_text="WhatsApp Business Account ID",
                        max_length=255,
                        verbose_name="WABA ID",
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        help_text="Permanent or temporary access token from Meta"
                    ),
                ),
                (
                    "webhook_verify_token",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Token you set in Meta webhook configuration",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_instances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Instance",
                "verbose_name_plural": "WhatsApp Instances",
                "ordering": ["-created_at"],
            },
        ),
    ]
